name: cicd-orange

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscription_id }}
        resourceGroupName: 'orange_rg'
        template: /arm/iac-orange.json
        parameters: 
          webappName=orangeApp00
     
    - name: Get WebApp/FunctionApp publish profile
      id: webapp-dev
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        resourceGroupName: 'orange_rg'
        appName: 'orangeApp00'
    
    - name: Moving build to artifacts directory
      run: more ${{ steps.webapp-dev.outputs.profile }}
    
    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.0.72
    #     inlineScript: |
    #         az account show

  build:
    name: build-orange
    needs: iac
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: orangeacr00.azurecr.io
        username: orangeacr00
        password: BUXBPl3szMpK7kxoruwdIlAsoT2LiB/x
    - run: |
        docker build -t orangeacr00.azurecr.io/img-orangev0 .
        docker push orangeacr00.azurecr.io/img-orangev0
  
  deploy:
    name: deploy-orange
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'orangeApp00'
        publish-profile: ${{ steps.webapp-dev.outputs.profile }}
        images: 'orangeacr00.azurecr.io/img-orangev0'
  
  test:
    name: test-orange E2E on Chrome
    needs: deploy
    runs-on: ubuntu-20.04
    # let's make sure our tests pass on Chrome browser
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome

