name: cicd-orange

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        login-server: orangeacrfree01.azurecr.io
        username: orangeAcrFree01
        password: AWtIUO2fbWSxgL9Rr00LiP+ILTgeOpJz
      run: |
        docker build . -t mycontainer.azurecr.io/myapp:${{ github.sha }}
        docker push mycontainer.azurecr.io/myapp:${{ github.sha }} 
        pwd  