name: cicd-orange

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  AZURE_RESOURCE_GROUP: orange_rg   # set this to your target resource group
  AZURE_WEBAPP_NAME: orange-webapp # set this to your target web app
  #AZURE_SUBSCRIPTIONID: f3c3a373-0239-4818-bf69-367b5ce29218 #

jobs:
  iac:
    name: IaaC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    #Login to Azure
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    #TODO: DELETE THIS LINES
    - name: Get ACR Admin
      run: echo az acr credential show --name orangeacr00 --query passwords[0].value

    #  # Deploy ARM template
    # - name: Run ARM deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     #subscriptionId: ${{ env.AZURE_SUSBCRIPTIONID }}
    #     resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
    #     template: ./arm-template/iac-orange.json
    #     parameters: webAppName=${{ env.AZURE_WEBAPP_NAME }}

  build:
    name: build
    needs: iac
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    #**Login to Azure
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    #Get publishing profile
    - name: Get WebApp4Containers publish profile
      id: webapp-dev
      uses: aliencube/publish-profile-actions@v1
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        appName: ${{ env.AZURE_WEBAPP_NAME }}
    #Get ACR Credentials
    - name: Get ACR Admin
      run: echo "ACR_PASS=$(az acr credential show --name orangeacr00 --query passwords[0].value)" >> $GITHUB_ENV
      id: get-acradmin
    #TODO: DELETE
    - name: PRINT ACR Admin
      run: echo ${{ env.ACR_PASS }}
    #Build image to ACR
    - uses: azure/docker-login@v1
      with:
        login-server: orangeacr00.azurecr.io
        username: orangeacr00
        password: ${{ env.ACR_PASS }}
    - run: |
        docker build -t orangeacr00.azurecr.io/img-orangev0 .
        docker push orangeacr00.azurecr.io/img-orangev0
  
  # deploy:
  #   name: deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #       publish-profile: ${{ steps.webapp-dev.outputs.profile }}
  #       images: 'orangeacr00.azurecr.io/img-orangev0'
  
  # test:
  #   name: test
  #   needs: deploy
  #   runs-on: ubuntu-20.04
  #   # let's make sure our tests pass on Chrome browser
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome

