name: cicd-orange

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Setup Java 1.8.x
      uses: actions/setup-java@v1
      with:
        # If your pom.xml <maven.compiler.source> version is not in 1.8.x,
        # change the Java version to match the version in pom.xml <maven.compiler.source>
        java-version: '1.8.x'

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: orangeacrfree01.azurecr.io
        username: orangeAcrFree01
        password: AWtIUO2fbWSxgL9Rr00LiP+ILTgeOpJz
    - run: |
        docker build . -t orangeacrfree01.azurecr.io/img-orange 
        docker push orangeacrfree01.azurecr.io/img-orange   
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'orangeApp01'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'mycontainer.azurecr.io/img-orange'
