name: cicd-orange

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: build-orange
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: orangeacrfree01.azurecr.io
        username: orangeAcrFree01
        password: AWtIUO2fbWSxgL9Rr00LiP+ILTgeOpJz
    - run: |
        docker build -t orangeacrfree01.azurecr.io/img-orangev2  .
        docker push orangeacrfree01.azurecr.io/img-orangev2   
        docker image ls
  
  deploy:
    name: deploy-orange
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8.x'
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'orangeApp01'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'orangeacrfree01.azurecr.io/img-orangev2'
