name: cicd-orange

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: build-orange
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: orangeacr00.azurecr.io
        username: orangeacr00
        password: BUXBPl3szMpK7kxoruwdIlAsoT2LiB/x
    - run: |
        docker build -t orangeacr00.azurecr.io/img-orangev0 .
        docker push orangeacr00.azurecr.io/img-orangev0
  
  deploy:
    name: deploy-orange
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'orangeApp00'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'orangeacr00.azurecr.io/img-orangev0'
