name: cicd-orange

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: build-orange
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: orangeacrfree02.azurecr.io
        username: orangeAcrFree02
        password: L4QR/ybxZsOyqIrOynt7VGnaW0EW0Bg4
    - run: |
        docker build -t orangeacrfree02.azurecr.io/img-orangev0 .
        docker push orangeacrfree02.azurecr.io/img-orangev0
  
  deploy:
    name: deploy-orange
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'orangeAPPmanual01'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'orangeacrfree02.azurecr.io/img-orangev0'
