# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      nameArray:
        description: 'Person to greet'
        default: 'World,OnePiece'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          echo "${{fromJSON(nameArray)}}"
